version: 0.0
os: linux
files:
  - source: /target/JavaWeb.war
    destination: /tmp/codedeploy-deployment-staging-area/
  - source: /scripts/configure_http_port.xsl
    destination: /tmp/codedeploy-deployment-staging-area/
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 120
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 120
  ApplicationStart:
    - location: scripts/write_codedeploy_config.sh
    - location: scripts/start_application.sh
      timeout: 120
  ValidateService:
    - location: scripts/basic_health_check.sh
